### ISSUE TITLE
How can I test this

### ISSUE THREAD

**Issue by brettsimington** [rock-walker/PdfCompression#1]
I download and try run app to test, but documentation very vague. Can you please provide more info on how to run a test?

**Comment by rock-walker** [comment]
Hi @brettsimington, do you still have exceptions?
Please look at app.config file and configure properly keys "sourcePdfFolder" and "destinationPdfFolder".
Or share please exception message for giving better piece of advice.

**Comment by maeni70** [comment]
I am looking for a library, which shows the decoding of JBIG2Decode, but this lib only supports DCTDecode and CCITTFaxDecode, correct?

**Comment by brettsimington** [comment]
Hi,

Thank you so much for reaching out to me. We went in another direction.
Thank you again.
